on:
  release:
    types: [created]
jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-node@v1
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"

      - name: Setup Git
        run: |
          git config --global user.name "Mayank"
          git config --global user.email "mayank-automate@noreply.github.com"

      - name: Update version
        run: npm version patch

      - name: Install & build
        run: npm i && npm run build

      - name: Save to GitHub
        run: |
          git config --global user.name "Mayank"
          git config --global user.email "mayank-automate@noreply.github.com"
          git fetch
          git checkout master
          git add .
          git status
          git commit -m "patch version"
          git push origin master

      - name: Publish tag to npm
        if: contains(github.ref, 'tags')
        working-directory: ./build
        run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - uses: actions/setup-node@v1
        with:
          registry-url: "https://npm.pkg.github.com"

      - name: Publish tag to GPR
        working-directory: ./build
        run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}
